name: untitled8
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.0
  http: ^1.2.0          # تحديث النسخة إذا لزم الأمر
  device_info_plus: ^9.0.0
  email_otp: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  

  fonts:
    - family: Pacifico
      fonts:
        - asset: font/Pacifico-Regular.ttf

    - family: Philosopher
      fonts:
        - asset: font/Philosopher-Regular.ttf



  assets:
    - lib/images/1.jpg
    - lib/images/q1.jpeg
